### ISSUE TITLE
shares always in English

### ISSUE THREAD

**Issue by MorphBC** [seedhodler/seedhodler-legacy#22]
While Phrase generated correctly in target language, split shares generated in English only!

**Comment by MorphBC** [comment]
As result recovered phrase also in English

**Comment by Auronmatrix** [comment]
That is because no wordlist for other languages have been created yet. I would recommend opening an issue with / or even beter a PR to https://github.com/trezor/python-shamir-mnemonic/tree/api-update/shamir_mnemonic
