### ISSUE TITLE
Split parts are too long for cryptosteel backups

### ISSUE THREAD

**Issue by efnats** [seedhodler/seedhodler-legacy#6]
Using the Trezor Model T the split parts consist of only 20 words each which makes backup with cryptosteel possible.
It would be very good if seedhodler would default to the same seed generation scheme.
I tried to combine the secrets to get behind the actual seed which was generated but couldnt find a working online implementation of the slip-0039.

**Comment by Auronmatrix** [comment]
Seedhodler already uses the SLIP-0039 implementation. However, there are some group rules currently hard coded which I suspect is the cause of the large parts. 

Will investigate this further

**Comment by Auronmatrix** [comment]
Also to be investigated if https://github.com/ilap/slip39-js (the slip-39) implementation we use complies with the slip-0039 specification from Satoshilabs

**Comment by efnats** [comment]
I meant to say that since the Trezor T is using slip0039 and still generates 20 words long shares, we should always default the UI to whatever generates shares that are no longer than 24 word so to enable cryptosteel backups.
When the user chooses other options like grouping etc obviously the shares will become longer.
