### ISSUE TITLE
introduction of groups destroys usability of simple shares generation

### ISSUE THREAD

**Issue by efnats** [seedhodler/seedhodler-legacy#8]
Since group support was added, to my understanding a user would generate a simple 3/5 share backup by adding each 1/1 share subgroups which is confusing.

Group support is very welcome, however this should be an extra feature in the UI that doesn't break the generation of simple shares.

**Comment by Auronmatrix** [comment]
Agreed. Simple is better. Will switch the defaults to generate a simple 3/5 without groups as default. 

Should the group options be hidden by default?

**Comment by Auronmatrix** [comment]
Perhaps a simple way to switch between simple and group share generation would be good
