### ISSUE TITLE
use of the word Mnemonic (let's not)

### ISSUE THREAD

**Issue by efnats** [seedhodler/seedhodler-legacy#9]
I suggest that we replace that word "Mnemonic" with "seed" whenever possible.
For example "generate seed"

In my opinion its easier to remember my actual seed than to spell "MNEMONIC". That word is ugly and I believe it's not going to hold in the crypto space for too long. Let's be the ones to help get rid of it. :)

**Comment by Auronmatrix** [comment]
This could be misleading to more technical users. The seed and the mnemonic is not the same thing. However, something in the middle could be clearer:

`seed phrase`
`seed words`
`seed recovery phrase`

Those would be some of my recommendations.
